
# file: monit/tasks/main.yml

- name: pkg - Install package Debian
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items: "{{ monit_pkg }}"
  when: ansible_os_family == "Debian"


- name: pkg - Install package RedHat
  yum:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items: "{{ monit_pkg }}"
  when: ansible_os_family == "RedHat"


- name: create includes folder
  file: path={{ monit_includes }} state=directory mode=0600

- name: config - Setup monitrc
  template:
    src: etc/monit/monitrc.j2
    dest: "{{monitrc_conf}}"
    owner: root
    group: root
    mode: 0700
  notify: restart monit

- name: monitors - Create facts directory
  file:
    path: "/etc/ansible/facts.d"
    mode: 0755
    state: directory

- name: monitors - Registers configured monitors
  template:
    src: "monit.fact.j2"
    dest: "/etc/ansible/facts.d/monit.fact"
    mode: 0644
  register: monit_write_facts

- name: monitors - Reload facts
  setup:
    filter: "ansible_local"
  when: monit_write_facts.changed

- name: Check if php-fpm is running
  shell: ps aux | grep php-fpm | grep -v grep
  ignore_errors: yes
  changed_when: false
  register: service_phpfpm_status

- name: Check if nginx is running
  shell: ps aux | grep nginx | grep -v grep
  ignore_errors: yes
  changed_when: false
  register: service_nginx_status

- name: monitors - Write monitors
  template:
    src: etc/monit/conf.d/monitor.j2
    dest: "{{ monit_includes }}/{{ item.name }}"
    owner: root
    group: root
  with_items: "{{ monit_services }}"
  notify: restart monit

- name: monitors - List configured monitors
  command: ls -1 {{ monit_includes }}
  register: monit_services_present
  changed_when: false

- name: monitors - Remove unused monitors
  file:
    path: "{{ monit_includes }}/{{ item }}"
    state: absent
  with_items: monit_services_present.stdout_lines
  when: monit_service_delete_unlisted and item|basename not in ansible_local.monit.monit_configured_services
  notify: restart monit

- name: create monitoring folder
  file: path=/root/bin/hr/ state=directory mode=0755

- name: Copy monitoring script
  template:
    src: highload-report.sh.j2
    dest: "/root/bin/hr/highload-report.sh"
    owner: root
    group: root
    mode: 0755
