
# file: monit/tasks/main.yml

- name: pkg - Install package
  apt:
    name: monit
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: create includes folder
  file: path={{ monit_includes }} state=directory mode=0600

- name: config - Setup monitrc
  template:
    src: etc/monit/monitrc.j2
    dest: "{{monitrc_conf}}"
    owner: root
    group: root
    mode: 0700
  notify: restart monit

- name: monitors - Write monitors
  template:
    src: etc/monit/conf.d/monitor.j2
    dest: "{{ monit_includes }}/{{ item.name }}"
    owner: root
    group: root
  with_items: "{{ monit_services }}"
  notify: restart monit


- name: Copy monitoring script
  copy: src=highload-report.sh dest=/root/bin/hr/ owner=root mode=755
